# Generated by Django 4.2.4 on 2023-09-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(blank=-2, upload_to='project_images'),
        ),
    ]
